{{- if .Values.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  entryPoints:
    {{- range .Values.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.routes }}
    - match: {{ .match }}
      kind: Rule
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ .service.name }}
          port: {{ .service.port }}
    {{- end }}
{{- end }}

{{- if .Values.middlewares }}
{{- range .Values.middlewares }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
spec:
  {{- toYaml .spec | nindent 4 }}
{{- end }}
{{- end }}