apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-go-service.fullname" . }}
  labels:
    {{- include "generic-go-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8889
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.service.grpc.enabled }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "generic-go-service.labels" . | nindent 4 }}
