apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.env.JWT_SECRET | b64enc }}
  google-client-id: {{ .Values.env.GOOGLE_CLIENT_ID | b64enc }}