replicaCount: 1
namespace: r-clone

generic-go-service:

  image:
    repository: ghcr.io/guliguligagaga/place-test/auth
    tag: main
  service:
    port: 8080
    name: auth
  env:
    JWT_SECRET: "test"
    GIN_MODE: release
    GOOGLE_CLIENT_ID: "test"

env:
  JWT_SECRET: "test"
  GIN_MODE: release
  GOOGLE_CLIENT_ID: "test"