name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}

    - name: Build and push auth
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        build-args: SERVICE_NAME=auth
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/auth:${{ github.sha }}

    - name: Build and push draw
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        build-args: SERVICE_NAME=draw
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/draw:${{ github.sha }}

    - name: Build and push grid
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        build-args: SERVICE_NAME=grid
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/grid:${{ github.sha }}

    - name: Build and push websocket
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        build-args: SERVICE_NAME=websocket
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/websocket:${{ github.sha }}
